version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"

    # Apply default reviewer to created
    # pull requests
    default_reviewers:
      - "adrianmwli"
